[server]
host = "0.0.0.0"
port = 2333
password = "youshallnotpass"

[route_planner]
enabled = false
cidrs = []
excluded_ips = []

[sources]
youtube = true
spotify = true
http = true
local = false
jiosaavn = true

[mirrors]
providers = [
  #"ytsearch:\"%ISRC%\"",
  #"ytsearch:%QUERY%",
  "jssearch:%QUERY%"
]

# The decryption configuration for the JioSaavn tracks
[jiosaavn]
search_limit = 10 # Limit number of search results
recommendations_limit = 10 # Limit number of recommendation results
playlist_load_limit = 50 # Limit tracks for playlists
album_load_limit = 50 # Limit tracks for albums
artist_load_limit = 20 # Limit tracks for artist top songs

[jiosaavn.decryption]
secretKey = "38346591" # The required secret key used for decryption
# algorithm = "DES" # The algorithm used for decryption (Default "DES")
# transformation = "DES/ECB/PKCS5Padding" # The transformation used for decryption (Default "DES/ECB/PKCS5Padding")

[jiosaavn.proxy]
url = "http://proxy.example.com:8080"
# Optional authentication
username = "myuser"
password = "mypassword"

[filters]
volume = true
equalizer = true
karaoke = true
timescale = true
tremolo = true
vibrato = true
distortion = true
rotation = true
channel_mix = true
low_pass = true

[logging]
level = "info"
# Optional: detailed module overrides. Example: "rustalink=debug,tokio=warn"
filters = "rustalink=debug"

[spotify]
playlist_load_limit = 6 # 0 = unlimited, 1 = 100 tracks, 2 = 200 tracks, etc.
album_load_limit = 6 # 0 = unlimited, 1 = 50 tracks, 2 = 100 tracks, etc.
search_limit = 10 # Limit number of search results
recommendations_limit = 10 # Limit number of recommendation results

playlist_page_load_concurrency = 10 # Number of playlist pages to fetch concurrently
album_page_load_concurrency = 5 # Number of album pages to fetch concurrently
track_resolve_concurrency = 50 # Number of tracks to resolve concurrently
