[server]
host = "0.0.0.0"
port = 2333
password = "youshallnotpass"

[route_planner]
enabled = false
cidrs = []
excluded_ips = []

[sources]
youtube = true
spotify = true
http = true
local = false
jiosaavn = true

# The decryption configuration for the JioSaavn tracks
[jiosaavn.decryption]
secretKey = "38346591" # The required secret key used for decryption
# algorithm = "DES" # The algorithm used for decryption (Default "DES")
# transformation = "DES/ECB/PKCS5Padding" # The transformation used for decryption (Default "DES/ECB/PKCS5Padding")

[filters]
volume = true
equalizer = true
karaoke = true
timescale = true
tremolo = true
vibrato = true
distortion = true
rotation = true
channel_mix = true
low_pass = true

[logging]
level = "info"
# Optional: detailed module overrides. Example: "rustalink=debug,tokio=warn"
filters = "rustalink=debug"
