[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "link-arg=-lm", "-C", "link-arg=-fno-stack-protector"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "link-arg=-lm", "-C", "link-arg=-fno-stack-protector"]
