[target.x86_64-unknown-linux-musl]
rustflags = [
  "-C", "link-arg=-lm",
  "-C", "link-arg=-lc",
  "-C", "target-feature=+crt-static",
]

[target.aarch64-unknown-linux-musl]
rustflags = [
  "-C", "link-arg=-lm",
  "-C", "link-arg=-lc",
  "-C", "target-feature=+crt-static",
]